version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_container_steam
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  shadow_db:
    image: postgres:latest
    container_name: postgres_shadow_steam
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main_shadow
    ports:
      - "5435:5432"
    volumes:
      - shadow_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-steam
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3006:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
      - shadow_db

volumes:
  db_data:
  shadow_db_data:
  pgadmin_data:
